name: shutterup
favicon: null
layout_spectrum: 0.48511211294680834
typography_spectrum: 0.5754793984815478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8570373321417719
  lightness: 0.3217127067036927
  saturation: 0.5057188395876437
  rhythmicContrast: 0.9818753038998693
purpose: []
